version: '1'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      -"4000:4000"
    links:
     - mongo
  mongo: 
    container_name: mongo
    image: mongo
      - ./data:/data/db
    ports:
      -"27017:27017"
